VENDOR_RULES: dict[str, str] = {
    # Meals & Entertainment
    "mcdonald": "Meals & Entertainment",
    "tim horton": "Meals & Entertainment",
    "starbucks": "Meals & Entertainment",
    "subway": "Meals & Entertainment",
    "boston pizza": "Meals & Entertainment",
    "a&w": "Meals & Entertainment",
    "white spot": "Meals & Entertainment",
    "denny": "Meals & Entertainment",
    "pizza hut": "Meals & Entertainment",
    "domino": "Meals & Entertainment",
    "kfc": "Meals & Entertainment",
    "dairy queen": "Meals & Entertainment",
    "burger king": "Meals & Entertainment",
    "pho": "Meals & Entertainment",
    "sushi": "Meals & Entertainment",
    "chinese restaurant": "Meals & Entertainment",
    "vietnamese": "Meals & Entertainment",
    "safeway": "Meals & Entertainment",
    "save-on-foods": "Meals & Entertainment",
    "save on foods": "Meals & Entertainment",
    "t&t": "Meals & Entertainment",
    "t & t": "Meals & Entertainment",
    "real canadian superstore": "Meals & Entertainment",
    "superstore": "Meals & Entertainment",
    "whole foods": "Meals & Entertainment",
    "costco": "Meals & Entertainment",
    "freshco": "Meals & Entertainment",
    "no frills": "Meals & Entertainment",
    # Travel & Transport
    "uber": "Travel & Transport",
    "lyft": "Travel & Transport",
    "esso": "Travel & Transport",
    "shell": "Travel & Transport",
    "petro-canada": "Travel & Transport",
    "petro canada": "Travel & Transport",
    "husky": "Travel & Transport",
    "chevron": "Travel & Transport",
    "bc ferries": "Travel & Transport",
    "translink": "Travel & Transport",
    "compass card": "Travel & Transport",
    "hertz": "Travel & Transport",
    "avis": "Travel & Transport",
    "enterprise rent": "Travel & Transport",
    "budget rent": "Travel & Transport",
    "air canada": "Travel & Transport",
    "westjet": "Travel & Transport",
    "marriott": "Travel & Transport",
    "hilton": "Travel & Transport",
    "holiday inn": "Travel & Transport",
    "best western": "Travel & Transport",
    "delta hotel": "Travel & Transport",
    "hyatt": "Travel & Transport",
    "fairmont": "Travel & Transport",
    # Office Supplies
    "staples": "Office Supplies",
    "best buy": "Office Supplies",
    "london drugs": "Office Supplies",
    "grand & toy": "Office Supplies",
    "ikea": "Office Supplies",
    "home depot": "Office Supplies",
    "rona": "Office Supplies",
    "henry's": "Office Supplies",
    "the source": "Office Supplies",
    "memory express": "Office Supplies",
    "canada computers": "Office Supplies",
    # Utilities & Software
    "telus": "Utilities & Software",
    "shaw": "Utilities & Software",
    "rogers": "Utilities & Software",
    "bell canada": "Utilities & Software",
    "fido": "Utilities & Software",
    "koodo": "Utilities & Software",
    "virgin mobile": "Utilities & Software",
    "microsoft": "Utilities & Software",
    "adobe": "Utilities & Software",
    "amazon web services": "Utilities & Software",
    "aws": "Utilities & Software",
    "google cloud": "Utilities & Software",
    "dropbox": "Utilities & Software",
    "slack": "Utilities & Software",
    "zoom": "Utilities & Software",
    "github": "Utilities & Software",
    "atlassian": "Utilities & Software",
    "notion": "Utilities & Software",
    "bc hydro": "Utilities & Software",
    "fortis bc": "Utilities & Software",
}

KEYWORD_RULES: dict[str, str] = {
    # Meals & Entertainment
    "coffee": "Meals & Entertainment",
    "lunch": "Meals & Entertainment",
    "dinner": "Meals & Entertainment",
    "breakfast": "Meals & Entertainment",
    "restaurant": "Meals & Entertainment",
    "cafe": "Meals & Entertainment",
    "grocery": "Meals & Entertainment",
    "groceries": "Meals & Entertainment",
    "food": "Meals & Entertainment",
    "beverage": "Meals & Entertainment",
    "snack": "Meals & Entertainment",
    # Travel & Transport
    "fuel": "Travel & Transport",
    "gasoline": "Travel & Transport",
    "gas station": "Travel & Transport",
    "parking": "Travel & Transport",
    "toll": "Travel & Transport",
    "airfare": "Travel & Transport",
    "airline": "Travel & Transport",
    "flight": "Travel & Transport",
    "hotel": "Travel & Transport",
    "motel": "Travel & Transport",
    "car rental": "Travel & Transport",
    "taxi": "Travel & Transport",
    "transit": "Travel & Transport",
    "mileage": "Travel & Transport",
    # Office Supplies
    "printer": "Office Supplies",
    "paper": "Office Supplies",
    "ink cartridge": "Office Supplies",
    "toner": "Office Supplies",
    "stationery": "Office Supplies",
    "office chair": "Office Supplies",
    "desk": "Office Supplies",
    "laptop": "Office Supplies",
    "monitor": "Office Supplies",
    "keyboard": "Office Supplies",
    "mouse": "Office Supplies",
    "usb": "Office Supplies",
    "hard drive": "Office Supplies",
    # Utilities & Software
    "subscription": "Utilities & Software",
    "internet": "Utilities & Software",
    "software": "Utilities & Software",
    "phone bill": "Utilities & Software",
    "electricity": "Utilities & Software",
    "hydro": "Utilities & Software",
    "natural gas": "Utilities & Software",
    "cloud storage": "Utilities & Software",
    "domain": "Utilities & Software",
    "hosting": "Utilities & Software",
    "licence": "Utilities & Software",
    "license": "Utilities & Software",
}
